[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend"
  functions = "netlify/functions"
  package = "frontend"

[build.environment]
  NODE_VERSION = "16"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "frontend"
  functions = "netlify/functions"
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 