[build]
  base = "."
  command = "cd frontend && npm install --legacy-peer-deps --force --no-audit && CI=false ./node_modules/.bin/cross-env GENERATE_SOURCEMAP=false react-scripts build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force --no-audit"
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 