# Global settings applied to the whole site
[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps"
  GENERATE_SOURCEMAP = "false"

# Production context: all deploys from the Production branch set in your site's settings
[context.production]
  command = "cd frontend && npm install && npm run build"

# Deploy Preview context: all deploys resulting from a pull/merge request
[context.deploy-preview]
  command = "cd frontend && npm install && npm run build"

# Branch Deploy context: all deploys that are not from a pull/merge request
[context.branch-deploy]
  command = "cd frontend && npm install && npm run build"

# Development context: used when running netlify dev
[dev]
  command = "cd frontend && npm start"
  port = 3000
  targetPort = 3000
  publish = "frontend/build"
  functions = "netlify/functions"
  functionsPort = 9999

# Redirects for handling client-side routing and API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 